# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myservice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmyservice.proto\x12\tmyservice\"\x1c\n\tmyRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1e\n\nmyResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x83\x01\n\tMyService\x12:\n\tMyMethod1\x12\x14.myservice.myRequest\x1a\x15.myservice.myResponse\"\x00\x12:\n\tMyMethod2\x12\x14.myservice.myRequest\x1a\x15.myservice.myResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=30
  _globals['_MYREQUEST']._serialized_end=58
  _globals['_MYRESPONSE']._serialized_start=60
  _globals['_MYRESPONSE']._serialized_end=90
  _globals['_MYSERVICE']._serialized_start=93
  _globals['_MYSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
